ProjectPastel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectPastel.Data;
using ProjectPastel.Models;

namespace ProjectPastel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        public HomeController(ApplicationDbContext context)
        {
            _context = context; 
        }

        public IActionResult SelectProject()
        {
            return View(); 
        }
        

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectPastel/Controllers/SponsoredProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectPastel.Data;
using ProjectPastel.Models;

namespace ProjectPastel.Controllers
{
    public class SponsoredProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SponsoredProjectsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SponsoredProjects
        public async Task<IActionResult> Index()
        {
            return View(await _context.SponsoredProject.ToListAsync());
        }

        // GET: SponsoredProjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sponsoredProject = await _context.SponsoredProject
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sponsoredProject == null)
            {
                return NotFound();
            }

            return View(sponsoredProject);
        }

        // GET: SponsoredProjects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SponsoredProjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SponsorName,Title,Description,Contacts,InScope,OutOfScope,SkillRequirements,RelatedProjects,TeamSize,Duration,IsAllocated")] SponsoredProject sponsoredProject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sponsoredProject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sponsoredProject);
        }

        // GET: SponsoredProjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sponsoredProject = await _context.SponsoredProject.FindAsync(id);
            if (sponsoredProject == null)
            {
                return NotFound();
            }
            return View(sponsoredProject);
        }

        // POST: SponsoredProjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SponsorName,Title,Description,Contacts,InScope,OutOfScope,SkillRequirements,RelatedProjects,TeamSize,Duration,IsAllocated")] SponsoredProject sponsoredProject)
        {
            if (id != sponsoredProject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sponsoredProject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SponsoredProjectExists(sponsoredProject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sponsoredProject);
        }

        // GET: SponsoredProjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sponsoredProject = await _context.SponsoredProject
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sponsoredProject == null)
            {
                return NotFound();
            }

            return View(sponsoredProject);
        }

        // POST: SponsoredProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sponsoredProject = await _context.SponsoredProject.FindAsync(id);
            _context.SponsoredProject.Remove(sponsoredProject);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SponsoredProjectExists(int id)
        {
            return _context.SponsoredProject.Any(e => e.Id == id);
        }
    }
}

ProjectPastel/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ProjectPastel/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjectPastel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="parallax_scrolling">
    <div class="dark_background">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
                <div class="oxygen">
                    <h1>Project Pastel</h1>
                    <h2>Home Page</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
        <div class="mainPageButton" onclick="@("window.location.href='" + Url.Action("Create", "SponsoredProjects") + "'");">
            <h1>For Sponsors</h1>
            <h2>Submit your projects here.</h2>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
        <div class="mainPageButton" onclick="@("window.location.href='" + Url.Action("SelectProject", "Home") + "'");">
            <h1>For Students</h1>
            <h2>Submit your preferences here.</h2>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
        <div class="mainPageButton">
            <h1>For Convenors</h1>
            <h2>For all your admin needs.</h2>
        </div>
    </div>
</div>

ProjectPastel/Views/Home/SelectProject.cshtml
@{
    ViewData["Title"] = "SelectProject";
}

@using ProjectPastel.Models

<div class="parallax_scrolling">
    <div class="dark_background">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
                <div class="oxygen">
                    <h1>Project Pastel</h1>
                    <h2>Project Preferences</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<!--

    ALRIGHT SO

    We're using Models\GroupPreferences and Models\SponsoredProject, have a gander and hopefully it's easy enough

    I was following this tutorial
    https://odetocode.com/blogs/scott/archive/2013/03/11/dropdownlistfor-with-asp-net-mvc.aspx

    Well, "Tutorial" - There's a comment where he assumes the List is populated from a database or elsewhere
    Which is all well and good, except I have no idea how to do that. 

-->

<hr />
<div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">

        @model ParentModel
        @{ 

            //Model.GroupPreferences.projectsList.Add

        }
        @using (Html.BeginForm())
        {
            @Html.LabelFor(o => o.GroupPreferences.GroupName)
            @Html.EditorFor(o => o.GroupPreferences.GroupName)

            <p></p> // Too lazy to figure out line breaks

            @Html.LabelFor(o => o.GroupPreferences.Preference1)
            @Html.EditorFor(o => o.GroupPreferences.Preference1)

            <p></p>

            @Html.LabelFor(o => o.GroupPreferences.Preference2)
            @Html.EditorFor(o => o.GroupPreferences.Preference2)

            <p></p>
            //@Html.LabelFor(o => o.GroupPreferences)
            //@Html.DropDownListFor(o => o.GroupPreferences.selectedProjectId3, Model.GroupPreferences.ProjectItems3)
            //@Html.ValidationMessageFor(o => o.GroupPreferences.selectedProjectId3)

        }

    </div>
</div>